### ISSUE TITLE
Generated SQL does not place a space or line break before FROM and WHERE

### ISSUE THREAD

**Issue by bmmathe** [landmarkhw/Dapper.GraphQL#28]
Any particular reason where there wouldn't be a space or line break before my FROM and WHERE keywords?  I'm following the sample exactly and the generated SQL won't run because the select fields don't have a space or line break before the FROM so it looks like this:  

SELECT table.Column1, table.Column2FROM Table tableWHERE 1 = 1

**Comment by bmmathe** [comment]
Ah, I don't think you can use the word 'order' as your alias.  Maybe it's the ending 'r' that throws off the replaces?  Not sure but when I changed it to 'o' it works fine.

**Comment by dougrday** [comment]
That sounds like a strange behavior.  There are some bugs with the official `Dapper.SqlBuilder` library that we're using to generate the SQL, we may consider writing our own to get past it.

Do you have a code sample that you could share that reproduces the problem?

**Comment by bmmathe** [comment]
This was a stupid mistake on my part.  I was using "order" as my alias but that is a SQL reserved keyword so SQL Server was blowing up.  I changed the alias to "o" and it works fine.

**Comment by narbit** [comment]
> Any particular reason where there wouldn't be a space or line break before my FROM and WHERE keywords? I'm following the sample exactly and the generated SQL won't run because the select fields don't have a space or line break before the FROM so it looks like this:
> 
> SELECT table.Column1, table.Column2FROM Table tableWHERE 1 = 1

I almost filed a bug for this last week myself but turned out it was just a display issue with Visual Studio quick watch window.  And any text editor for that reason unless you enable show all characters. 

The template for the queries is stored in QueryTemplate and assigned in SqlQueryContext(). It looks like this:
`QueryTemplate = SqlBuilder.AddTemplate($@"SELECT
/**select**/
FROM {from}/**innerjoin**//**leftjoin**//**rightjoin**//**join**/
/**where**//**orderby**/");
        }`

In the quick watch, it would appear that templated/replaced items are stuck together with the FROM clause. But in reality they are separated with "\r" - a carriage return. If you watch your queries go through SQL Profiler, they look and get executed just fine.

**Comment by dougrday** [comment]
Gotcha.  Sounds like this can be closed for now then, thanks all for investigating :)
